# Generated by Django 6.0.1 on 2026-08-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_booking_balance_due_booking_deposit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
    ]
