# Generated by Django 6.0.1 on 2026-08-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_hotelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Needs Cleaning'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
