# Generated by Django 5.0.6 on 2026-09-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
